### ISSUE TITLE
Error dependencies

### ISSUE THREAD

**Issue by aka0kuro** [valorekhov/ovos-arch-linux#1]
It gives me the following dependencies error.

make: Circular python-ovos-core <- ovos-core dependency dropped.
make: Circular python-ovos-messagebus <- ovos-core dependency dropped.
##### Building PKGBUILDs-extra/python-combo-lock/ with makepkg -srif --noconfirm 
==> Making package: python-combo-lock 0.2.5-00 (Tue Jul 18 11:18:16 2023)
==> Checking runtime dependencies...
==> Installing missing dependencies...
error: target not found: python-memory-tempfile
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> python-memory-tempfile
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
make: *** [Makefile:59: PKGBUILDs-extra/python-combo-lock/*.pkg.tar.zst] Error 8

**Comment by valorekhov** [comment]
This should be resolved now with the latest commits. I tested a "from scratch" source install #3 on the Mark II target and resolved all issues with hardware initialization and package building.

The only issue I haven't looked into is the Homescreen skill loading with an apparent delay. However, the Assistant is operational and is responding to the "What Time Is It?" voice inquiry.

**Comment by aka0kuro** [comment]
Dependency error again.
==> Making package: ovos-shell 0f3335b0aa3a806b130a6a79299d79c75bc12c0e-0 (Wed Jul 19 11:36:26 2023)
==> Checking runtime dependencies...
==> Installing missing dependencies...
error: target not found: mycroft-gui
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> mycroft-gui
  -> qt5-virtualkeyboard
  -> qt5-lottie
  -> breeze-icons
  -> gst-plugin-va
  -> libva-utils
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.

**Comment by aka0kuro** [comment]
Thank you for your work.

**Comment by valorekhov** [comment]
The build of the earlier step `mycroft-gui` failed. The most usual cause is that the installation of the package failed even though it was build. I added a README note using your example here explaining the situation:
https://github.com/valorekhov/ovos-arch-linux#troubleshooting-incomplete-builds

To proceed further run `make mycroft-gui-qt5`. If it quits right away, delete the package files in PKGBUILDs\mycroft-gui-qt5 and re-run make, or install them manually with `pacman -U` If  you see an error, do share it here.

I also have just published already-built packages. See here if it suits your needs better:
https://github.com/valorekhov/ovos-arch-linux#installing-from-the-ovos-arch-package-repository
As a disclaimer: I never tested cutting over from a halfway completed source build to package install. It should work in theory, but theory is different in practice.

Thank you for testing!

**Comment by valorekhov** [comment]
You will also need to build  or pacman-install `python-ovos-vad-plugin-webrtcvad`, `python-ovos-stt-plugin-server`, 'python-ovos-ww-plugin-precise-lite' as they were missed as dependencies of dinkum listener, the default listener per the shipped config.

**Comment by valorekhov** [comment]
Based on what you reported in #2, the install did work and I am closing this issue
